// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Belt_Array = require("bs-platform/lib/js/belt_Array.js");

var Describe = {};

var Test = {};

function results(mock) {
  return Belt_Array.map(mock.mock.results, (function (result) {
                var match = result.type;
                if (match === "return") {
                  return {
                          TAG: /* Return */0,
                          _0: result.value
                        };
                } else if (match === "throw") {
                  return {
                          TAG: /* Throw */1,
                          _0: result.value
                        };
                } else {
                  return /* Imcomplete */0;
                }
              }));
}

var Mock = {
  results: results
};

var Expect = {};

var anyInt = (function () { return expect.any(Number) });

var anyFloat = (function () { return expect.any(Number) });

var anyString = (function () { return expect.any(String) });

var ExpectStatic = {
  anyInt: anyInt,
  anyFloat: anyFloat,
  anyString: anyString
};

var JestJs = {};

exports.Describe = Describe;
exports.Test = Test;
exports.Mock = Mock;
exports.Expect = Expect;
exports.ExpectStatic = ExpectStatic;
exports.JestJs = JestJs;
/* No side effect */
